# Generated by Django 5.0.1 on 2024-01-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Release_date', models.DateField()),
                ('Image', models.URLField()),
                ('Author', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Release_date', models.DateField()),
                ('Image', models.URLField()),
                ('Publisher', models.CharField(max_length=100)),
                ('Content_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Release_date', models.DateField()),
                ('Image', models.URLField()),
                ('Director', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=50)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
